### ISSUE TITLE
SQLSTATE[HY093] on "initListMyObjectAssociatedsPKs"

### ISSUE THREAD

**Issue by lionelbzv** [VanTanev/EqualNestBehavior#10]
Hi,

I just installed the behavior (with sf2.1 & propel 1.6.7 env) and encountered a problem in the "initListMyObjectAssociatedsPKs" method:

<code>SQLSTATE[HY093]: Invalid parameter number
500 Internal Server Error - PDOException </code>

It seems the bindValue doesn't work properly.

Thanks.

**Comment by willdurand** [comment]
error 500?

**Comment by lionelbzv** [comment]
This part of code fails:

<code>
$stmt = $con->prepare($sql);
$stmt->bindValue(':id', $this->getPrimaryKey(), PDO::PARAM_INT);
$stmt->execute();
</code>

If I use this method to bind values, it works:

<code>
$sql = "SELECT ... WHERE ... = ? ... AND  ... = ?" // i just change ":id" by "?"

$stmt->bindValue(1, $this->getPrimaryKey(), PDO::PARAM_INT);
$stmt->bindValue(2, $this->getPrimaryKey(), PDO::PARAM_INT);
</code>

**Comment by willdurand** [comment]
I wonder why it's not covered by tests.. What is your failing code?

## 

William Durand | http://www.williamdurand.fr

**Comment by lionelbzv** [comment]
I'm talking about the base propel generated code of my "Product" object (BaseProduct.php):

<code>
    /**
     \* Initializes the list of Equal Nest ProductAssociateds PKs.
     *
     \* This will query the database for Equal Nest ProductAssociateds relations to this Product object.
     \* It will set the list to an empty array if the object is newly created.
     *
     \* @param PropelPDO $con
     */
    protected function initListProductAssociatedsPKs(PropelPDO $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection(ProductPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

```
    if (null === $this->listEqualNestProductAssociatedsPKs) {
        if ($this->isNew()) {
            $this->listEqualNestProductAssociatedsPKs = array();
        } else {
            $sql = "
SELECT DISTINCT product.id
FROM product
INNER JOIN product_associated ON
product.id = product_associated.product_1
OR
product.id = product_associated.product_2
WHERE
product.id IN (
    SELECT product_associated.product_1
    FROM product_associated
    WHERE product_associated.product_2 = :id
)
OR
product.id IN (
    SELECT product_associated.product_2
    FROM product_associated
    WHERE product_associated.product_1 = :id
)";

            $stmt = $con->prepare($sql);
            $stmt->bindValue(':id', $this->getPrimaryKey(), PDO::PARAM_INT);
            $stmt->execute();

            $this->listEqualNestProductAssociatedsPKs = $stmt->fetchAll(PDO::FETCH_COLUMN);
        }
    }
}
```

</code>

**Comment by willdurand** [comment]
Ah ok. Weird because it should work..

**Comment by VanTanev** [comment]
It really should work, and is covered by unit tests - this is basically the main part of the behavior. 

What is your exact error, and php version?

**Comment by lionelbzv** [comment]
I'm using the php version delivered with ubuntu ("PHP 5.3.10-1ubuntu3.4")

SF2 Stack Trace:

<code>
Stack Trace

```
in /home/user/www/My Project v1.0/vendor/propel/propel1/runtime/lib/connection/DebugPDOStatement.php at line 90  -+
        public function execute($input_parameters = null)
        {
            $debug    = $this->pdo->getDebugSnapshot();
            $return    = parent::execute($input_parameters);
            $sql = $this->getExecutedQueryString();
            $this->pdo->log($sql, null, __METHOD__, $debug);
at PDOStatement ->execute (null)
in /home/user/www/My Project v1.0/vendor/propel/propel1/runtime/lib/connection/DebugPDOStatement.php at line 90  -+
at DebugPDOStatement ->execute ()
in /home/user/www/My Project v1.0/src/SlaviaVintage/Model/om/BaseProduct.php at line 4216  -+
at BaseProduct ->initListProductAssociatedsPKs (null)
in /home/user/www/My Project v1.0/src/SlaviaVintage/Model/om/BaseProduct.php at line 4279  -+
at BaseProduct ->getProductAssociateds ()
in /home/user/www/My Project v1.0/vendor/symfony/symfony/src/Symfony/Component/Form/Util/PropertyPath.php at line 410  -
```

</code>

**Comment by VanTanev** [comment]
I see no reason this should be happening, but then again, I don't see a problem with moving to a positional bindValue().

@willdurand agree?

@StudioEcho could you open a pull request?

**Comment by willdurand** [comment]
Well, why not but I'd like to understand the issue before merging a fix.

## 

William Durand | http://www.williamdurand.fr

**Comment by lionelbzv** [comment]
OK for the pull request, but I had to train myself cause I'm beginner in github's stuff... i'll see that tomorrow! :)

**Comment by VanTanev** [comment]
To me it sounds like an issue with the particular version of PDO, it makes
no sense otherwise.
