### ISSUE TITLE
Update Packagist after repo switch

### ISSUE THREAD

**Issue by sgrodzicki** [VanTanev/EqualNestBehavior#13]
@VanTanev could you please update repository details at Packagist after the repo has changed? Packagist has still old information:

https://packagist.org/packages/craftyshadow/propel-equalnest-behavior

**Comment by willdurand** [comment]
:+1:

**Comment by VanTanev** [comment]
It should be ok now, but can someone verify?

**Comment by sgrodzicki** [comment]
Yeah, it's OK now.
