### ISSUE TITLE
Handling Schema is missing

### ISSUE THREAD

**Issue by skowron-line** [VanTanev/EqualNestBehavior#16]
Hi Ivan, Im trying to handle schema in Your behavior, but schema handling is not working when I have

``` xml
<database schema="dd">

  <table name="test">
  <!-- ... -->
  </table>

  <table name="test_test" phpName="TestTest">
      <vendor type="mysql">
          <parameter name="Engine" value="InnoDB"/>
          <parameter name="Charset" value="utf8"/>
          <parameter name="Collate" value="utf8_polish_ci"/>
      </vendor>
      <behavior name="equal_nest">
          <parameter name="parent_table" value="test"/>
          <parameter name="reference_column_1" value="test_id"/>
          <parameter name="reference_column_2" value="test2_id"/>
      </behavior>
  </table>

</database>
```

after trying to rebuild my models, i get

> Fatal error: Call to a member function getPrimaryKey() on a non-object in /.../vendor/craftyshadow/propel-equalnest-behavior/src/EqualNestBehavior.php on line 35

If I change

``` xml
          <parameter name="parent_table" value="dd.test"/>
```

i get error

> Execution of target "om-template" failed for the following reason: /.../vendor/propel/propel1/generator/build-propel.xml:538:56: Table "dd.test" contains a foreign key to nonexistent table "test"

Sorry about my english, hope you got it.

Greetings from Poland
skowron-line

**Comment by VanTanev** [comment]
I have never used the `schema` option, so I am a little stumped on this problem.

**Comment by skowron-line** [comment]
@VanTanev You should add `schema` parameter and 
https://github.com/VanTanev/EqualNestBehavior/blob/master/src/EqualNestBehavior.php#L150 here You should create `tableName` using `schema` (if defined) + `tableName`.

Edit:
if You define `schema` in table or database tag, table names are created as `schema.name`

**Comment by VanTanev** [comment]
I cannot replicate this locally.

I think that you may have an error in the schema of your "test" table. Can you post your actual schema (with some names replaced if necessary)?

**Comment by skowron-line** [comment]
``` xml
<database name="tt" defaultIdMethod="native" namespace="Test\SkillsBundle\Model" schema="test">
    <table name="skill" phpName="Skill" idMethod="native">
        <vendor type="mysql">
            <parameter name="Engine" value="InnoDB"/>
            <parameter name="Charset" value="utf8"/>
        </vendor>
        <column name="id" phpName="Id" type="INTEGER" primaryKey="true" required="true" autoIncrement="true"/>
        <column name="name" phpName="Name" type="VARCHAR" size="128" required="true"/>
    </table>

    <table name="skill_similarity" phpName="SkillSimilarity">
            <vendor type="mysql">
                <parameter name="Engine" value="InnoDB"/>
                <parameter name="Charset" value="utf8"/>
                <parameter name="Collate" value="utf8_polish_ci"/>
            </vendor>
            <behavior name="equal_nest">
                <parameter name="parent_table" value="skill"/>
                <parameter name="reference_column_1" value="similarity_id"/>
                <parameter name="reference_column_2" value="skill_id"/>
            </behavior>
        </table>
</database>
```

**Comment by VanTanev** [comment]
Sorry, but I am unable to reproduce this error. Feel free to write a test case that shows it and I will reopen the issue.
