### ISSUE TITLE
Propel2 compatibility

### ISSUE THREAD

**Issue by lionelbzv** [VanTanev/EqualNestBehavior#17]
Hello,

Can we use this behavior "as is" with Propel2-alpha5?

Thanks!

**Comment by VanTanev** [comment]
I wouldn't think so. This plugin has only been tested against Propel 1.6, and there is currently no planned update to Propel 2. 

If you think the plugin can be useful in your own projects, and have the time for it, I'd be interested to hear if making it Propel 2 is even feasible without a full rewrite. Though, it probably can't be compatible with both versions at the same time.
