### ISSUE TITLE
What about tagging a first stable version?

### ISSUE THREAD

**Issue by willdurand** [VanTanev/EqualNestBehavior#5]
I think we could tag a first stable version, let's say `1.0.0`. What do you think?

**Comment by VanTanev** [comment]
I hadn't noticed you opening this issue. Just tested the plugin in the project where I originally used it and everything seems to work fine (hooray for integration tests :))

Will tag 1.0.0

**Comment by willdurand** [comment]
Perfect, thanks! And, yes, now we have a really strong behavior!
