### ISSUE TITLE
Allow to use the behavior twice on the same "parent"

### ISSUE THREAD

**Issue by willdurand** [VanTanev/EqualNestBehavior#6]

**Comment by willdurand** [comment]
Closing for now. I won't be able to work on it..

**Comment by jkabat** [comment]
@willdurand @VanTanev is there any other solution I could use instead?

I have used my RecommendedProduct with the equal nest behavior (parent: Product). I need another equal nest in ProductAccessory (parent: Product). Currently Im stuck... how can I solve this issue? Any suggestions?

**Comment by VanTanev** [comment]
As of right now, this project is not actively developed; What you're asking for is outside the specified behavior.

Sorry to say, but I'm currently engaged in other projects and cannot work on this.
