### ISSUE TITLE
What about unidirectional relations?

### ISSUE THREAD

**Issue by kasitmp** [VanTanev/EqualNestBehavior#7]
I tried to build a follower/followee relation. I have 2 tables, a user table and a cross-reference table called follower_followee.
The logic should be that a user can be a follower of another user who would be the followee. The problem is that the equalNestBehavior seems to build up bi directional relations, so if Alice follows Bob, Bob is automatically follower of Alice.
Is there a way to have it the correct way? Alice follows Bob, but Bob does not follow Alice only because of this?

**Comment by willdurand** [comment]
I think it's not the aim of this behavior.

**Comment by VanTanev** [comment]
Yeah, the whole purpose of the Equal Nest behavior is to provide an equal nest relationship model. If you need unidirectional relations, you can use the behavior as a base to develop what you're after, but it should be its own separate thing.
