### ISSUE TITLE
compatibility with versionable behavior?

### ISSUE THREAD

**Issue by rayrigam** [VanTanev/EqualNestBehavior#8]
isVersioningNecessary does not seem to consider the methods used by the EqualNest behavior, thus a new version is NOT created when adding "friends" to any given "person" object. The data in the array type columns  (such as "person_friend_ids" and "person_friend_versions") created by Versionable behavior in the "version" table, is out of phase with the insertion of "friends". "friends" are only added to the version table in a subsequent version to the one they were actually inserted, since it is only until the execution of methods like "getPersonFriendRelatedByPersonId()" that the data is stored in the dedicated columns of the "version" table.

**Comment by willdurand** [comment]
There is nothing about compatibility with the versionable behavior at the moment.
